name: API KEY HEROKU STAGING

on: [push]
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - name: Deploy to Heroku
      uses: behe/heroku-build@v1
      with:
        app-name: "your-app-name-on-heroku"
        api-key: "${{secrets.HEROKU_API_KEY}}"