name: API KEY HEROKU STAGING

on:
  push:
    branches:
      - develop
      
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    needs: test-unit
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install npm dependencies
      run: npm install
    - name: Run build task
      run: npm run build --if-present
    - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.1.0
      with:
        api_key: ${{secrets.HEROKU_API_KEY}}
        email: ${{secrets.HEROKU_EMAIL}}
        app_name: fast-harbor-95243
        heroku_branch: "main"
        subfolder: "dist-staging"